# Generated by Django 4.2 on 2023-06-16 14:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0002_remove_receipt_store'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Receipt',
            new_name='ReceiptItem',
        ),
    ]
