# Generated by Django 4.2 on 2023-06-20 23:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0006_category_receiptitem_category'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='receiptitem',
            name='category',
        ),
        migrations.DeleteModel(
            name='Category',
        ),
    ]
