# Generated by Django 4.2 on 2023-06-30 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('receipts', '0011_alter_receipt_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='receipt',
            name='total',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
        migrations.AlterField(
            model_name='receiptitem',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=20),
        ),
    ]
